
# Show the current folder in the prompt.
PS1='(debian)\w $ '

# Allow aliases to work with sudo, i.e.: "sudo ll".
alias sudo='sudo '

# List the most recent files.
alias l='ls -ltr | tail -10'

alias ls='ls --color=auto'
alias ll='ls -l'
alias n='nimble'

# This docker container supports three versions of nim. To use the
# standard 1.4.2 package, comment out the following path
# modifications.

# Use prebuild 1.6.12 x86 version.
# export PATH=/home/teamaster/nim-1.6.12/bin:$PATH export

# Use manually built version.
# * cd ~/Nim
# * git checkout v1.6.12
# * ./build_all.sh
# * nim -v
export PATH=/home/teamaster/Nim/bin:$PATH

