#!/bin/bash

# Run statictea tests from the command line.
#
# cd ~/code/statictea
# src/test
#
# To add a new test do the following:
#
# * Add a new test command line to the testcommands.txt file.
# * Add test files to the testfiles folder.

# todo: move this to the tests folder

# Run from the static tea folder.
if [[ "$(pwd)" != "/Users/steve/code/statictea" ]]; then
  echo "run from statictea folder"
  echo "src/test"
  exit 1
fi

# Test commands run from the testfiles folder.
cd testfiles

# Run each line in the testcommands.txt file.
rc=0 # success
while read -r cmd
do
  # Skip lines that start with #.
  if [[ $cmd == \#* ]]; then
    continue
  fi
  # Skip blank lines.
  if [[ $cmd == "" ]]; then
    continue
  fi

  echo "$cmd"
  eval "$cmd"
  if [ $? != 0 ]; then
    echo "Error: cmd failed."
    echo
    cat t.txt
    echo
    rc=1
  fi
done < "../src/testcommands.txt"
exit $rc
